# Generated by Django 5.2.17 on 2026-10-06 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearplan",
            name="closed_through",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Last completed month: 0–12. Completed months use actuals only.",
                validators=[django.core.validators.MaxValueValidator(12)],
            ),
        ),
        migrations.AlterField(
            model_name="yearplan",
            name="year",
            field=models.PositiveIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("primary", True)),
                fields=("primary",),
                name="one_primary_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.UniqueConstraint(
                fields=("entry", "category"), name="one_split_per_category"
            ),
        ),
    ]
