# Generated by Django 5.2.17 on 2026-10-07 11:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_entry_bank_category_entry_bank_merchant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="account",
        ),
        migrations.CreateModel(
            name="CategorySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999999999999),
                        ]
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("six_monthly", "Every six months"),
                            ("annual", "Annual"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "due_month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "original_amount_cents",
                    models.PositiveBigIntegerField(editable=False),
                ),
                ("original_frequency", models.CharField(editable=False, max_length=12)),
                (
                    "original_due_month",
                    models.PositiveSmallIntegerField(editable=False),
                ),
                ("original_due_day", models.PositiveSmallIntegerField(editable=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="budget.category",
                    ),
                ),
                (
                    "year_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_schedules",
                        to="budget.yearplan",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "year_plan"),
                        name="one_category_schedule_per_year",
                    )
                ],
            },
        ),
    ]
