# Generated by Django 5.2.17 on 2026-10-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_remove_category_account_categoryschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="income_month",
            field=models.DateField(
                blank=True,
                help_text="Income budget month (use its first day). Blank uses the payment month.",
                null=True,
            ),
        ),
    ]
