# Generated by Django 5.2.17 on 2026-10-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_alter_entry_account_alter_entry_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("transaction", "Transaction"),
                    ("savings", "Savings"),
                    ("credit_card", "Credit Card"),
                ],
                default="transaction",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="matched_transfer",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="card_receipt",
                to="budget.entry",
            ),
        ),
    ]
